remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Michael Oelschlager's CS-499 Demo ePortfolio
description: This site is meant to showcase the ePortfolio developed for CS-499 (Computer Science Capstone)


