{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "efe00752-d837-4281-80be-2b85d8a3e39c",
   "metadata": {},
   "outputs": [
    {
     "ename": "IndentationError",
     "evalue": "expected an indented block (2867879518.py, line 565)",
     "output_type": "error",
     "traceback": [
      "\u001b[1;36m  Cell \u001b[1;32mIn[1], line 565\u001b[1;36m\u001b[0m\n\u001b[1;33m    greenButton = Button(24)\u001b[0m\n\u001b[1;37m    ^\u001b[0m\n\u001b[1;31mIndentationError\u001b[0m\u001b[1;31m:\u001b[0m expected an indented block\n"
     ]
    }
   ],
   "source": [
    "#\n",
    "# Thermostat - This is the Python code used to demonstrate\n",
    "# the functionality of the thermostat that we have prototyped throughout\n",
    "# the course. \n",
    "#\n",
    "# This code works with the test circuit that was built for module 7.\n",
    "#\n",
    "# Functionality:\n",
    "#\n",
    "# The thermostat has three states: off, heat, cool\n",
    "#\n",
    "# The lights will represent the state that the thermostat is in.\n",
    "#\n",
    "# If the thermostat is set to off, the lights will both be off.\n",
    "#\n",
    "# If the thermostat is set to heat, the Red LED will be fading in \n",
    "# and out if the current temperature is blow the set temperature;\n",
    "# otherwise, the Red LED will be on solid.\n",
    "#\n",
    "# If the thermostat is set to cool, the Blue LED will be fading in \n",
    "# and out if the current temperature is above the set temperature;\n",
    "# otherwise, the Blue LED will be on solid.\n",
    "#\n",
    "# One button will cycle through the three states of the thermostat.\n",
    "#\n",
    "# One button will raise the setpoint by a degree.\n",
    "#\n",
    "# One button will lower the setpoint by a degree.\n",
    "#\n",
    "# The LCD display will display the date and time on one line and\n",
    "# alternate the second line between the current temperature and \n",
    "# the state of the thermostat along with its set temperature.\n",
    "#\n",
    "# The Thermostat will send a status update to the TemperatureServer\n",
    "# over the serial port every 30 seconds in a comma delimited string\n",
    "# including the state of the thermostat, the current temperature\n",
    "# in degrees Fahrenheit, and the setpoint of the thermostat.\n",
    "#\n",
    "#------------------------------------------------------------------\n",
    "# Change History\n",
    "#------------------------------------------------------------------\n",
    "# Version   |   Description\n",
    "#------------------------------------------------------------------\n",
    "#    1          Initial Development\n",
    "#------------------------------------------------------------------\n",
    "\n",
    "##\n",
    "## Import necessary to provide timing in the main loop\n",
    "##\n",
    "from time import sleep\n",
    "from datetime import datetime\n",
    "\n",
    "##\n",
    "## Imports required to allow us to build a fully functional state machine\n",
    "##\n",
    "# Note: My computer doesn't seen to have the statemachine module installed\n",
    "#!pip install statemachine\n",
    "from statemachine import StateMachine, State\n",
    "\n",
    "##\n",
    "## Imports necessary to provide connectivity to the \n",
    "## thermostat sensor and the I2C bus\n",
    "##\n",
    "import board\n",
    "import adafruit_ahtx0\n",
    "\n",
    "##\n",
    "## These are the packages that we need to pull in so that we can work\n",
    "## with the GPIO interface on the Raspberry Pi board and work with\n",
    "## the 16x2 LCD display\n",
    "##\n",
    "# import board - already imported for I2C connectivity\n",
    "import digitalio\n",
    "import adafruit_character_lcd.character_lcd as characterlcd\n",
    "\n",
    "## This imports the Python serial package to handle communications over the\n",
    "## Raspberry Pi's serial port. \n",
    "import serial\n",
    "\n",
    "##\n",
    "## Imports required to handle our Button, and our PWMLED devices\n",
    "##\n",
    "from gpiozero import Button, PWMLED\n",
    "\n",
    "##\n",
    "## This package is necessary so that we can delegate the blinking\n",
    "## lights to their own thread so that more work can be done at the\n",
    "## same time\n",
    "##\n",
    "from threading import Thread\n",
    "\n",
    "##\n",
    "## This is needed to get coherent matching of temperatures.\n",
    "##\n",
    "from math import floor\n",
    "\n",
    "##\n",
    "## Imports needed for linear regression machine learning algorithm for Enhancement 3\n",
    "##\n",
    "import matplotlib.pyplot as plt\n",
    "import sklearn\n",
    "import numpy as np\n",
    "import csv\n",
    "from sklearn import model_selection\n",
    "from sklearn import linear_model\n",
    "\n",
    "##\n",
    "## DEBUG flag - boolean value to indicate whether or not to print \n",
    "## status messages on the console of the program\n",
    "## \n",
    "DEBUG = True\n",
    "\n",
    "##\n",
    "## Create an I2C instance so that we can communicate with\n",
    "## devices on the I2C bus.\n",
    "##\n",
    "i2c = board.I2C()\n",
    "\n",
    "##\n",
    "## Initialize our Temperature and Humidity sensor\n",
    "##\n",
    "thSensor = adafruit_ahtx0.AHTx0(i2c)\n",
    "\n",
    "##\n",
    "## Initialize our serial connection\n",
    "##\n",
    "## Because we imported the entire package instead of just importing Serial and\n",
    "## some of the other flags from the serial package, we need to reference those\n",
    "## objects with dot notation.\n",
    "##\n",
    "## e.g. ser = serial.Serial\n",
    "##\n",
    "ser = serial.Serial(\n",
    "        port='/dev/ttyS0', # This would be /dev/ttyAM0 prior to Raspberry Pi 3\n",
    "        baudrate = 115200, # This sets the speed of the serial interface in\n",
    "                           # bits/second\n",
    "        parity=serial.PARITY_NONE,      # Disable parity\n",
    "        stopbits=serial.STOPBITS_ONE,   # Serial protocol will use one stop bit\n",
    "        bytesize=serial.EIGHTBITS,      # We are using 8-bit bytes \n",
    "        timeout=1          # Configure a 1-second timeout\n",
    ")\n",
    "\n",
    "##\n",
    "## Our two LEDs, utilizing GPIO 18, and GPIO 23\n",
    "##\n",
    "redLight = PWMLED(18)\n",
    "blueLight = PWMLED(23)\n",
    "\n",
    "\n",
    "##\n",
    "## ManagedDisplay - Class intended to manage the 16x2 \n",
    "## Display\n",
    "##\n",
    "## This code is largely taken from the work done in module 4, and\n",
    "## converted into a class so that we can more easily consume the \n",
    "## operational capabilities.\n",
    "##\n",
    "class ManagedDisplay():\n",
    "    ##\n",
    "    ## Class Initialization method to setup the display\n",
    "    ##\n",
    "    def __init__(self):\n",
    "        ##\n",
    "        ## Setup the six GPIO lines to communicate with the display.\n",
    "        ## This leverages the digitalio class to handle digital \n",
    "        ## outputs on the GPIO lines. There is also an analagous\n",
    "        ## class for analog IO.\n",
    "        ##\n",
    "        ## You need to make sure that the port mappings match the\n",
    "        ## physical wiring of the display interface to the \n",
    "        ## GPIO interface.\n",
    "        ##\n",
    "        ## compatible with all versions of RPI as of Jan. 2019\n",
    "        ##\n",
    "        self.lcd_rs = digitalio.DigitalInOut(board.D17)\n",
    "        self.lcd_en = digitalio.DigitalInOut(board.D27)\n",
    "        self.lcd_d4 = digitalio.DigitalInOut(board.D5)\n",
    "        self.lcd_d5 = digitalio.DigitalInOut(board.D6)\n",
    "        self.lcd_d6 = digitalio.DigitalInOut(board.D13)\n",
    "        self.lcd_d7 = digitalio.DigitalInOut(board.D26)\n",
    "\n",
    "        # Modify this if you have a different sized character LCD\n",
    "        self.lcd_columns = 16\n",
    "        self.lcd_rows = 2 \n",
    "\n",
    "        # Initialise the lcd class\n",
    "        self.lcd = characterlcd.Character_LCD_Mono(self.lcd_rs, self.lcd_en, \n",
    "                    self.lcd_d4, self.lcd_d5, self.lcd_d6, self.lcd_d7, \n",
    "                    self.lcd_columns, self.lcd_rows)\n",
    "\n",
    "        # wipe LCD screen before we start\n",
    "        self.lcd.clear()\n",
    "\n",
    "    ##\n",
    "    ## cleanupDisplay - Method used to cleanup the digitalIO lines that\n",
    "    ## are used to run the display.\n",
    "    ##\n",
    "    def cleanupDisplay(self):\n",
    "        # Clear the LCD first - otherwise we won't be abe to update it.\n",
    "        self.lcd.clear()\n",
    "        self.lcd_rs.deinit()\n",
    "        self.lcd_en.deinit()\n",
    "        self.lcd_d4.deinit()\n",
    "        self.lcd_d5.deinit()\n",
    "        self.lcd_d6.deinit()\n",
    "        self.lcd_d7.deinit()\n",
    "        \n",
    "    ##\n",
    "    ## clear - Convenience method used to clear the display\n",
    "    ##\n",
    "    def clear(self):\n",
    "        self.lcd.clear()\n",
    "\n",
    "    ##\n",
    "    ## updateScreen - Convenience method used to update the message.\n",
    "    ##\n",
    "    def updateScreen(self, message):\n",
    "        self.lcd.clear()\n",
    "        self.lcd.message = message\n",
    "\n",
    "    ##\n",
    "    ## setupDisplay - Transfers the functionality for operating the lcd display\n",
    "    ##  from the manageMyDisplay function to the ManagedDisplay class\n",
    "    ##\n",
    "    def setupDisplay(current_time, currentTempF, currentState, setPointTemp, counter):\n",
    "        ## Setup display line 1\n",
    "        lcd_line_1 = current_time.strftime(\"%b %d  %H:%M:%S\\n\")\n",
    "\n",
    "        ## Setup Display Line 2\n",
    "        if(counter < 6):\n",
    "            lcd_line_2 = f\"T:{currentTempF:0.1f}F\"\n",
    "        else:\n",
    "            lcd_line_2 = f\"ST:{currentState} Set:{setPointTemp}F\"\n",
    "\n",
    "        ## Output both lines together\n",
    "        lcd_display = lcd_line_1 + lcd_line_2\n",
    "        return lcd_display\n",
    "\n",
    "    ## End class ManagedDisplay definition  \n",
    "\n",
    "##\n",
    "## Initialize our display\n",
    "##\n",
    "screen = ManagedDisplay()\n",
    "\n",
    "##\n",
    "## TemperatureMachine - This is our StateMachine implementation class.\n",
    "## The purpose of this state machine is to manage the three states\n",
    "## handled by our thermostat:\n",
    "##\n",
    "##  off\n",
    "##  heat\n",
    "##  cool\n",
    "##\n",
    "##\n",
    "class TemperatureMachine(StateMachine):\n",
    "    \"A state machine designed to manage our thermostat\"\n",
    "\n",
    "    ##\n",
    "    ## Define the three states for our machine.\n",
    "    ##\n",
    "    ##  off - nothing lit up\n",
    "    ##  red - only red LED fading in and out\n",
    "    ##  blue - only blue LED fading in and out\n",
    "    ##\n",
    "    off = State(initial = True)\n",
    "    heat = State()\n",
    "    cool = State()\n",
    "\n",
    "    ##\n",
    "    ## Default temperature setPoint is 72 degrees Fahrenheit\n",
    "    ##\n",
    "    setPoint = 72\n",
    "\n",
    "    ##\n",
    "    ## cycle - event that provides the state machine behavior\n",
    "    ## of transitioning between the three states of our \n",
    "    ## thermostat\n",
    "    ##\n",
    "    cycle = (\n",
    "        off.to(heat) |\n",
    "        heat.to(cool) |\n",
    "        cool.to(off)\n",
    "    )\n",
    "\n",
    "    ##\n",
    "    ## on_enter_heat - Action performed when the state machine transitions\n",
    "    ## into the 'heat' state\n",
    "    ##\n",
    "    def on_enter_heat(self):\n",
    "        self.updateLights()\n",
    "        if(DEBUG):\n",
    "            print(\"* Changing state to heat\")\n",
    "\n",
    "    ##\n",
    "    ## on_exit_heat - Action performed when the statemachine transitions\n",
    "    ## out of the 'heat' state.\n",
    "    ##\n",
    "    def on_exit_heat(self):\n",
    "        redLight.off()\n",
    "    ##\n",
    "    ## on_enter_cool - Action performed when the state machine transitions\n",
    "    ## into the 'cool' state\n",
    "    ##\n",
    "    def on_enter_cool(self):\n",
    "        self.updateLights()\n",
    "        if(DEBUG):\n",
    "            print(\"* Changing state to cool\")\n",
    "    \n",
    "    ##\n",
    "    ## on_exit_cool - Action performed when the statemachine transitions\n",
    "    ## out of the 'cool' state.\n",
    "    ##\n",
    "    def on_exit_cool(self):\n",
    "        blueLight.off()\n",
    "    ##\n",
    "    ## on_enter_off - Action performed when the state machine transitions\n",
    "    ## into the 'off' state\n",
    "    ##\n",
    "    def on_enter_off(self):\n",
    "\n",
    "        redLight.off()\n",
    "        blueLight.off()\n",
    "        if(DEBUG):\n",
    "            print(\"* Changing state to off\")\n",
    "    \n",
    "    ##\n",
    "    ## processTempStateButton - Utility method used to send events to the \n",
    "    ## state machine. This is triggered by the button_pressed event\n",
    "    ## handler for our first button\n",
    "    ##\n",
    "    def processTempStateButton(self):\n",
    "        if(DEBUG):\n",
    "            print(\"Cycling Temperature State\")\n",
    "        self.send(\"cycle\")\n",
    "    ##\n",
    "    ## processTempIncButton - Utility method used to update the \n",
    "    ## setPoint for the temperature. This will increase the setPoint\n",
    "    ## by a single degree. This is triggered by the button_pressed event\n",
    "    ## handler for our second button\n",
    "    ##\n",
    "    def processTempIncButton(self):\n",
    "        if(DEBUG):\n",
    "            print(\"Increasing Set Point\")\n",
    "\n",
    "        self.setPoint = self.setPoint + 1\n",
    "        self.updateLights()\n",
    "    ##\n",
    "    ## processTempDecButton - Utility method used to update the \n",
    "    ## setPoint for the temperature. This will decrease the setPoint\n",
    "    ## by a single degree. This is triggered by the button_pressed event\n",
    "    ## handler for our third button\n",
    "    ##\n",
    "    def processTempDecButton(self):\n",
    "        if(DEBUG):\n",
    "            print(\"Decreasing Set Point\")\n",
    "\n",
    "        self.setPoint = self.setPoint - 1\n",
    "        self.updateLights()\n",
    "    ##\n",
    "    ## updateLights - Utility method to update the LED indicators on the \n",
    "    ## Thermostat\n",
    "    ##\n",
    "    def updateLights(self):\n",
    "        ## Make sure we are comparing temperatires in the correct scale\n",
    "        temp = floor(self.getFahrenheit())\n",
    "        redLight.off()\n",
    "        blueLight.off()\n",
    "    \n",
    "        ## Verify values for debug purposes\n",
    "        if(DEBUG):\n",
    "            print(f\"State: {self.current_state.id}\")\n",
    "            print(f\"SetPoint: {self.setPoint}\")\n",
    "            print(f\"Temp: {temp}\")\n",
    "\n",
    "        # Determine visual identifiers\n",
    "        if(self.current_state.id == 'heat'):\n",
    "            ## Heat\n",
    "            if(temp >= self.setPoint):\n",
    "                ## Already at preferred temp\n",
    "                redLight.on()\n",
    "            else:\n",
    "                ## Approaching preferred temp (heating)\n",
    "                redLight.pulse()\n",
    "        elif(self.current_state.id == 'cool'):\n",
    "            ## Cool\n",
    "            if(temp <= self.setPoint):\n",
    "                ## Already at preferred temp\n",
    "                blueLight.on()\n",
    "            else:\n",
    "                ## Approaching preferred temp (cooling)\n",
    "                blueLight.pulse()\n",
    "        else:\n",
    "            ## Off\n",
    "            pass\n",
    "    ##\n",
    "    ## run - kickoff the display management functionality of the thermostat\n",
    "    ##\n",
    "    def run(self):\n",
    "        myThread = Thread(target=self.manageMyDisplay)\n",
    "        myThread.start()\n",
    "\n",
    "    ##\n",
    "    ## Get the temperature in Fahrenheit\n",
    "    ##\n",
    "    def getFahrenheit(self):\n",
    "        t = thSensor.temperature\n",
    "        return (((9/5) * t) + 32)\n",
    "    \n",
    "    ##\n",
    "    ##  Configure output string for the Thermostat Server\n",
    "    ##\n",
    "    def setupSerialOutput(self):\n",
    "        output = f\"{tsm.current_state.id},{self.getFahrenheit():0.1f},{self.setPoint}/n\"\n",
    "        return output\n",
    "    \n",
    "    ## Continue display output\n",
    "    endDisplay = False\n",
    "\n",
    "    ##\n",
    "    ##  This function is designed to manage the LCD Display\n",
    "    ##\n",
    "    ## Note: Each function used in a program has a very small performance overhead.\n",
    "    ##  This shouldn't be a serious issue, but this change is optimizing the\n",
    "    ##  readability and maintainability of the program, not its efficiency. The program's\n",
    "    ##  memory seems to overwrite the same few variables without storing any data,\n",
    "    ##  except where it sends updates to a remote server which keeps track of data trends in its stead.\n",
    "    ##  This program doesn't handle much data, and so might not be a good fit for the Algorithms and Data\n",
    "    ##  Structures milestone. A better idea would be to develop a way to organize the data in the server,\n",
    "    ##  if I had any way to access the server or change its operations.\n",
    "    #\n",
    "    ## Splitting the functionality of this function into lcd display operations and server operations seems\n",
    "    ##  like it would be a good idea to improve the program's readability, but the two code segments are in\n",
    "    ##  the same place for a reason -- they use the same clock to time their operations. Moving the display\n",
    "    ##  functionality to another class would require running another while loop at the same time, which\n",
    "    ##  could noticeably impact the program's efficiency. The program is designed as embedded software, which\n",
    "    ##  means that making the code a bit less efficient in order to make it a bit more readable isn't a good\n",
    "    ##  trade-off. This can be fixed by removing the loop functionality from the lcd display functionality and\n",
    "    ##  simply calling the new setupDisplay function once every second.\n",
    "    def manageMyDisplay(self):\n",
    "        counter = 1\n",
    "        altCounter = 1\n",
    "        while not self.endDisplay:\n",
    "            ## Only display if the DEBUG flag is set\n",
    "            if(DEBUG):\n",
    "                print(\"Processing Display Info...\")\n",
    "    \n",
    "            ## Grab the current time(, temperature, state, and set point temperature)        \n",
    "            current_time = datetime.now()\n",
    "            current_temp = self.getFahrenheit()\n",
    "            current_state = tsm.current_state.id\n",
    "            setpoint_temp = tsm.setPoint\n",
    "\n",
    "            ## Set display message\n",
    "            lcd_display = screen.setupDisplay(current_time,\n",
    "                                              current_temp,\n",
    "                                              current_state,\n",
    "                                              setpoint_temp,\n",
    "                                              altCounter)\n",
    "            altCounter = altCounter + 1\n",
    "            if(altCounter >= 11):\n",
    "                # Run the routine to update the lights every 10 seconds\n",
    "                # to keep operations smooth\n",
    "                self.updateLights()\n",
    "                altCounter = 1\n",
    "    \n",
    "#           ## Setup display line 1\n",
    "#            lcd_line_1 = current_time.strftime(\"%b %d  %H:%M:%S\\n\")\n",
    "#\n",
    "#           ## Setup Display Line 2\n",
    "#            if(altCounter < 6):\n",
    "#                lcd_line_2 = f\"T:{self.getFahrenheit():0.1f}F\"\n",
    "#                altCounter = altCounter + 1\n",
    "#            else:\n",
    "#                lcd_line_2 = f\"ST:{tsm.current_state.id} Set:{tsm.setPoint}F\"\n",
    "#                altCounter = altCounter + 1\n",
    "#                if(altCounter >= 11):\n",
    "#                    # Run the routine to update the lights every 10 seconds\n",
    "#                    # to keep operations smooth\n",
    "#                    self.updateLights()\n",
    "#                    altCounter = 1\n",
    "    \n",
    "            ## Update Display\n",
    "            screen.updateScreen(lcd_display)\n",
    "    \n",
    "            ## Update server every 30 seconds\n",
    "            if(DEBUG):\n",
    "               print(f\"Counter: {counter}\")\n",
    "            if((counter % 30) == 0):\n",
    "                ser.write(self.setupSerialOutput().encode())\n",
    "                counter = 1\n",
    "            else:\n",
    "                counter = counter + 1\n",
    "            sleep(1)\n",
    "\n",
    "        ## Cleanup display\n",
    "        screen.cleanupDisplay()\n",
    "\n",
    "    ## End class TemperatureMachine definition\n",
    "\n",
    "##\n",
    "## Setup our State Machine\n",
    "##\n",
    "tsm = TemperatureMachine()\n",
    "tsm.run()\n",
    "\n",
    "\n",
    "##\n",
    "## MachineLearning - Class intended to manage the linear regression\n",
    "## chart for the accumulated temperature data and the machine learning\n",
    "## algorithm that will be implemented for the CS-499 Enhancement Two:\n",
    "## Algorithms and Data Structures\n",
    "##\n",
    "class MachineLearning():\n",
    "    ##\n",
    "    ## Build the lists\n",
    "    ##\n",
    "    stateList = []\n",
    "    tempList = []\n",
    "    setPointList = []\n",
    "    \n",
    "    ##\n",
    "    ## Populate the lists with data entries from the serial connection\n",
    "    ##\n",
    "    def listsFromSerial(self):        \n",
    "        try:\n",
    "            while True:\n",
    "                # Read a line from the serial port (adjust as per your data format)\n",
    "                line = ser.readline().decode('utf-8').strip()\n",
    "                \n",
    "                if line: # Process only if the string is not empty\n",
    "                    # Split the string by comma\n",
    "                    state, temp, setpoint = line.split(',')\n",
    "                    self.stateList.append(state)\n",
    "                    self.tempList.append(float(temp))\n",
    "                    self.setPointList.append(int(setpoint))\n",
    "\n",
    "                    if(DEBUG):\n",
    "                        print(f\"Appended: {line}\")\n",
    "                else:\n",
    "                    # If no data is received for 'timeout' seconds, break or handle as needed\n",
    "                    print(\"No more data from serial.\")\n",
    "                    break\n",
    "        except FileNotFoundError:\n",
    "            print(f\"Error: The serial connection was not found.\")\n",
    "        except Exception as e:\n",
    "            print(f\"An error occurred: {e}\")\n",
    "        \n",
    "    ##\n",
    "    ## Linear regression model to implement the machine learning functionality\n",
    "    ##\n",
    "    def linearModel(self):\n",
    "        ## Reshape the data to put each list entry into its own set of brackets,\n",
    "        ## then split the data into training and testing data sets\n",
    "        self.tempList = np.array(self.tempList).reshape(-1,1)\n",
    "        self.setPointList = np.array(self.setPointList).reshape(-1,1)\n",
    "        ## time variable in case of linear regression algorithm that uses time as a variable\n",
    "        # time = []\n",
    "        # for i in range(len(self.tempList)):\n",
    "        #     time.append(i * 30)\n",
    "\n",
    "        # tempTrain, tempTest, timeTrain, timeTest = model_selection.train_test_split(self.tempList, time, test_size = 0.2)\n",
    "        tempTrain, tempTest, setPointTrain, setPointTest = model_selection.train_test_split(self.tempList, self.setPointList, test_size = 0.2)\n",
    "\n",
    "        ## Model the linear regression algorithm for setPointTemperature / currentTemperature\n",
    "        model = linear_model.LinearRegression()\n",
    "        model.fit(setPointTrain, tempTrain)\n",
    "        accuracy = model.score(setPointTest, tempTest)\n",
    "        \n",
    "        if(DEBUG):\n",
    "            print(f\"Coefficient: {model.coef_}\")\n",
    "            print(f\"Intercept: {model.intercept_}\")\n",
    "            print(f\"Accuracy: {round(accuracy * 100, 2)}\")\n",
    "            \n",
    "    ## End class MachineLearning definition\n",
    "\n",
    "newThread = Thread(target=self.MachineLearning())\n",
    "newThread.start()\n",
    "\n",
    "##\n",
    "## Configure our green button to use GPIO 24 and to execute\n",
    "## the method to cycle the thermostat when pressed.\n",
    "##\n",
    "greenButton = Button(24)\n",
    "## Cycle thermostat state\n",
    "greenButton.when_pressed = tsm.processTempStateButton\n",
    "##\n",
    "## Configure our Red button to use GPIO 25 and to execute\n",
    "## the function to increase the setpoint by a degree.\n",
    "##\n",
    "redButton = Button(25)\n",
    "## Increase the setpoint by one degree Fahrenheit.\n",
    "redButton.when_pressed = tsm.processTempIncButton\n",
    "##\n",
    "## Configure our Blue button to use GPIO 12 and to execute\n",
    "## the function to decrease the setpoint by a degree.\n",
    "##\n",
    "blueButton = Button(12)\n",
    "## Decrease the setpoint by one degree Fahrenheit\n",
    "blueButton.when_pressed = tsm.processTempDecButton\n",
    "##\n",
    "## Setup loop variable\n",
    "##\n",
    "repeat = True\n",
    "\n",
    "##\n",
    "## Repeat until the user creates a keyboard interrupt (CTRL-C)\n",
    "##\n",
    "while repeat:\n",
    "    try:\n",
    "        ## wait\n",
    "        sleep(30)\n",
    "\n",
    "    except KeyboardInterrupt:\n",
    "        ## Catch the keyboard interrupt (CTRL-C) and exit cleanly\n",
    "        ## we do not need to manually clean up the GPIO pins, the \n",
    "        ## gpiozero library handles that process.\n",
    "        print(\"Cleaning up. Exiting...\")\n",
    "\n",
    "        ## Stop the loop\n",
    "        repeat = False\n",
    "        \n",
    "        ## Close down the display\n",
    "        tsm.endDisplay = True\n",
    "        sleep(1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fa601231-3f43-47ce-b00a-ce1a97bbf128",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "CS-499 Kernel",
   "language": "python",
   "name": "tutorial_env"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
